# Generated by Django 5.0.6 on 2024-06-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyerUsername', models.CharField(max_length=100)),
                ('buyerPhonenum', models.CharField(max_length=15)),
                ('buyerPassword', models.CharField(max_length=255)),
                ('farmerAddress', models.CharField(max_length=100)),
            ],
        ),
    ]
