# Generated by Django 5.0.6 on 2024-06-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='farmerAddress',
            new_name='buyerAddress',
        ),
    ]
