# Generated by Django 5.0.6 on 2024-06-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_rename_farmeraddress_buyer_buyeraddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='buyer',
            new_name='buyerdb',
        ),
    ]
